leftnav:
- identifier: 112fdee6-4ac6-84fc-6acb-d8c96fa3bb5a
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 1a5c083b-7d59-272d-b371-02fb33fea30a
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 5af5d2c9-64d4-81fd-c331-4483fcd3e249
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 05621971-aa5b-faf5-ff4c-f96a107e0569
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
